var wms_layers = [];


        var lyr_GoogleSatellite_0 = new ol.layer.Tile({
            'title': 'Google Satellite',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}'
            })
        });
var format_SolomonIslands_1 = new ol.format.GeoJSON();
var features_SolomonIslands_1 = format_SolomonIslands_1.readFeatures(json_SolomonIslands_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_SolomonIslands_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_SolomonIslands_1.addFeatures(features_SolomonIslands_1);
var lyr_SolomonIslands_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_SolomonIslands_1, 
                style: style_SolomonIslands_1,
                popuplayertitle: 'Solomon Islands',
                interactive: false,
                title: '<img src="styles/legend/SolomonIslands_1.png" /> Solomon Islands'
            });
var format_WASHinSchoolsBinsforMenstrualMaterials_2 = new ol.format.GeoJSON();
var features_WASHinSchoolsBinsforMenstrualMaterials_2 = format_WASHinSchoolsBinsforMenstrualMaterials_2.readFeatures(json_WASHinSchoolsBinsforMenstrualMaterials_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsBinsforMenstrualMaterials_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsBinsforMenstrualMaterials_2.addFeatures(features_WASHinSchoolsBinsforMenstrualMaterials_2);
var lyr_WASHinSchoolsBinsforMenstrualMaterials_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsBinsforMenstrualMaterials_2, 
                style: style_WASHinSchoolsBinsforMenstrualMaterials_2,
                popuplayertitle: 'WASH in Schools — Bins for Menstrual Materials',
                interactive: true,
    title: 'WASH in Schools — Bins for Menstrual Materials<br />\
    <img src="styles/legend/WASHinSchoolsBinsforMenstrualMaterials_2_0.png" /> No<br />\
    <img src="styles/legend/WASHinSchoolsBinsforMenstrualMaterials_2_1.png" /> Don\'t know/can\'t say<br />\
    <img src="styles/legend/WASHinSchoolsBinsforMenstrualMaterials_2_2.png" /> Yes<br />' });
var format_WASHinSchoolsNumberofHandwashingFacilities_3 = new ol.format.GeoJSON();
var features_WASHinSchoolsNumberofHandwashingFacilities_3 = format_WASHinSchoolsNumberofHandwashingFacilities_3.readFeatures(json_WASHinSchoolsNumberofHandwashingFacilities_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsNumberofHandwashingFacilities_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsNumberofHandwashingFacilities_3.addFeatures(features_WASHinSchoolsNumberofHandwashingFacilities_3);
var lyr_WASHinSchoolsNumberofHandwashingFacilities_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsNumberofHandwashingFacilities_3, 
                style: style_WASHinSchoolsNumberofHandwashingFacilities_3,
                popuplayertitle: 'WASH in Schools — Number of Handwashing Facilities',
                interactive: true,
    title: 'WASH in Schools — Number of Handwashing Facilities<br />\
    <img src="styles/legend/WASHinSchoolsNumberofHandwashingFacilities_3_0.png" /> 0 - 2<br />\
    <img src="styles/legend/WASHinSchoolsNumberofHandwashingFacilities_3_1.png" /> 2 - 7<br />\
    <img src="styles/legend/WASHinSchoolsNumberofHandwashingFacilities_3_2.png" /> 7 - 16<br />\
    <img src="styles/legend/WASHinSchoolsNumberofHandwashingFacilities_3_3.png" /> 16 - 35<br />\
    <img src="styles/legend/WASHinSchoolsNumberofHandwashingFacilities_3_4.png" /> 35 - 65<br />' });
var format_WASHinSchoolsAccessibleToiletsforPWD_4 = new ol.format.GeoJSON();
var features_WASHinSchoolsAccessibleToiletsforPWD_4 = format_WASHinSchoolsAccessibleToiletsforPWD_4.readFeatures(json_WASHinSchoolsAccessibleToiletsforPWD_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsAccessibleToiletsforPWD_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsAccessibleToiletsforPWD_4.addFeatures(features_WASHinSchoolsAccessibleToiletsforPWD_4);
var lyr_WASHinSchoolsAccessibleToiletsforPWD_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsAccessibleToiletsforPWD_4, 
                style: style_WASHinSchoolsAccessibleToiletsforPWD_4,
                popuplayertitle: 'WASH in Schools — Accessible Toilets for PWD',
                interactive: true,
    title: 'WASH in Schools — Accessible Toilets for PWD<br />\
    <img src="styles/legend/WASHinSchoolsAccessibleToiletsforPWD_4_0.png" /> false<br />\
    <img src="styles/legend/WASHinSchoolsAccessibleToiletsforPWD_4_1.png" /> true<br />' });
var format_WASHinSchoolsNumberofBoysToilets_5 = new ol.format.GeoJSON();
var features_WASHinSchoolsNumberofBoysToilets_5 = format_WASHinSchoolsNumberofBoysToilets_5.readFeatures(json_WASHinSchoolsNumberofBoysToilets_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsNumberofBoysToilets_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsNumberofBoysToilets_5.addFeatures(features_WASHinSchoolsNumberofBoysToilets_5);
var lyr_WASHinSchoolsNumberofBoysToilets_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsNumberofBoysToilets_5, 
                style: style_WASHinSchoolsNumberofBoysToilets_5,
                popuplayertitle: 'WASH in Schools — Number of Boy\'s Toilets',
                interactive: true,
    title: 'WASH in Schools — Number of Boy\'s Toilets<br />\
    <img src="styles/legend/WASHinSchoolsNumberofBoysToilets_5_0.png" /> 0 - 1<br />\
    <img src="styles/legend/WASHinSchoolsNumberofBoysToilets_5_1.png" /> 1 - 2<br />\
    <img src="styles/legend/WASHinSchoolsNumberofBoysToilets_5_2.png" /> 2 - 6<br />\
    <img src="styles/legend/WASHinSchoolsNumberofBoysToilets_5_3.png" /> 6 - 18<br />\
    <img src="styles/legend/WASHinSchoolsNumberofBoysToilets_5_4.png" /> 18 - 33<br />' });
var format_WASHinSchoolsNumberofGirlsToilets_6 = new ol.format.GeoJSON();
var features_WASHinSchoolsNumberofGirlsToilets_6 = format_WASHinSchoolsNumberofGirlsToilets_6.readFeatures(json_WASHinSchoolsNumberofGirlsToilets_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsNumberofGirlsToilets_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsNumberofGirlsToilets_6.addFeatures(features_WASHinSchoolsNumberofGirlsToilets_6);
var lyr_WASHinSchoolsNumberofGirlsToilets_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsNumberofGirlsToilets_6, 
                style: style_WASHinSchoolsNumberofGirlsToilets_6,
                popuplayertitle: 'WASH in Schools — Number of Girl\'s Toilets',
                interactive: true,
    title: 'WASH in Schools — Number of Girl\'s Toilets<br />\
    <img src="styles/legend/WASHinSchoolsNumberofGirlsToilets_6_0.png" /> 0 - 1<br />\
    <img src="styles/legend/WASHinSchoolsNumberofGirlsToilets_6_1.png" /> 1 - 4<br />\
    <img src="styles/legend/WASHinSchoolsNumberofGirlsToilets_6_2.png" /> 4 - 8<br />\
    <img src="styles/legend/WASHinSchoolsNumberofGirlsToilets_6_3.png" /> 8 - 17<br />\
    <img src="styles/legend/WASHinSchoolsNumberofGirlsToilets_6_4.png" /> 17 - 37<br />' });
var format_WASHinSchoolsGenderSeparatedToilets_7 = new ol.format.GeoJSON();
var features_WASHinSchoolsGenderSeparatedToilets_7 = format_WASHinSchoolsGenderSeparatedToilets_7.readFeatures(json_WASHinSchoolsGenderSeparatedToilets_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsGenderSeparatedToilets_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsGenderSeparatedToilets_7.addFeatures(features_WASHinSchoolsGenderSeparatedToilets_7);
var lyr_WASHinSchoolsGenderSeparatedToilets_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsGenderSeparatedToilets_7, 
                style: style_WASHinSchoolsGenderSeparatedToilets_7,
                popuplayertitle: 'WASH in Schools — Gender Separated Toilets',
                interactive: true,
    title: 'WASH in Schools — Gender Separated Toilets<br />\
    <img src="styles/legend/WASHinSchoolsGenderSeparatedToilets_7_0.png" /> No<br />\
    <img src="styles/legend/WASHinSchoolsGenderSeparatedToilets_7_1.png" /> Dont know / Cant say<br />\
    <img src="styles/legend/WASHinSchoolsGenderSeparatedToilets_7_2.png" /> Yes<br />' });
var format_WASHinSchoolsNumberofStudentToilets_8 = new ol.format.GeoJSON();
var features_WASHinSchoolsNumberofStudentToilets_8 = format_WASHinSchoolsNumberofStudentToilets_8.readFeatures(json_WASHinSchoolsNumberofStudentToilets_8, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsNumberofStudentToilets_8 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsNumberofStudentToilets_8.addFeatures(features_WASHinSchoolsNumberofStudentToilets_8);
var lyr_WASHinSchoolsNumberofStudentToilets_8 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsNumberofStudentToilets_8, 
                style: style_WASHinSchoolsNumberofStudentToilets_8,
                popuplayertitle: 'WASH in Schools — Number of Student Toilets',
                interactive: true,
    title: 'WASH in Schools — Number of Student Toilets<br />\
    <img src="styles/legend/WASHinSchoolsNumberofStudentToilets_8_0.png" /> 0 - 2<br />\
    <img src="styles/legend/WASHinSchoolsNumberofStudentToilets_8_1.png" /> 2 - 7<br />\
    <img src="styles/legend/WASHinSchoolsNumberofStudentToilets_8_2.png" /> 7 - 15<br />\
    <img src="styles/legend/WASHinSchoolsNumberofStudentToilets_8_3.png" /> 15 - 31<br />\
    <img src="styles/legend/WASHinSchoolsNumberofStudentToilets_8_4.png" /> 31 - 70<br />' });
var format_WASHinSchoolsNumberofDrinkingWaterPoints_9 = new ol.format.GeoJSON();
var features_WASHinSchoolsNumberofDrinkingWaterPoints_9 = format_WASHinSchoolsNumberofDrinkingWaterPoints_9.readFeatures(json_WASHinSchoolsNumberofDrinkingWaterPoints_9, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsNumberofDrinkingWaterPoints_9 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsNumberofDrinkingWaterPoints_9.addFeatures(features_WASHinSchoolsNumberofDrinkingWaterPoints_9);
var lyr_WASHinSchoolsNumberofDrinkingWaterPoints_9 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsNumberofDrinkingWaterPoints_9, 
                style: style_WASHinSchoolsNumberofDrinkingWaterPoints_9,
                popuplayertitle: 'WASH in Schools — Number of Drinking Water Points',
                interactive: true,
    title: 'WASH in Schools — Number of Drinking Water Points<br />\
    <img src="styles/legend/WASHinSchoolsNumberofDrinkingWaterPoints_9_0.png" /> 0 - 2<br />\
    <img src="styles/legend/WASHinSchoolsNumberofDrinkingWaterPoints_9_1.png" /> 2 - 6<br />\
    <img src="styles/legend/WASHinSchoolsNumberofDrinkingWaterPoints_9_2.png" /> 6 - 13<br />\
    <img src="styles/legend/WASHinSchoolsNumberofDrinkingWaterPoints_9_3.png" /> 13 - 33<br />\
    <img src="styles/legend/WASHinSchoolsNumberofDrinkingWaterPoints_9_4.png" /> 33 - 100<br />' });
var format_WASHinSchoolsDrinkingWaterforPWD_10 = new ol.format.GeoJSON();
var features_WASHinSchoolsDrinkingWaterforPWD_10 = format_WASHinSchoolsDrinkingWaterforPWD_10.readFeatures(json_WASHinSchoolsDrinkingWaterforPWD_10, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsDrinkingWaterforPWD_10 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsDrinkingWaterforPWD_10.addFeatures(features_WASHinSchoolsDrinkingWaterforPWD_10);
var lyr_WASHinSchoolsDrinkingWaterforPWD_10 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsDrinkingWaterforPWD_10, 
                style: style_WASHinSchoolsDrinkingWaterforPWD_10,
                popuplayertitle: 'WASH in Schools — Drinking Water for PWD',
                interactive: true,
    title: 'WASH in Schools — Drinking Water for PWD<br />\
    <img src="styles/legend/WASHinSchoolsDrinkingWaterforPWD_10_0.png" /> No<br />\
    <img src="styles/legend/WASHinSchoolsDrinkingWaterforPWD_10_1.png" /> Don\'t know, can\'t say<br />\
    <img src="styles/legend/WASHinSchoolsDrinkingWaterforPWD_10_2.png" /> Yes<br />' });
var format_WASHinSchoolsConstantDrinkingWaterAvailability_11 = new ol.format.GeoJSON();
var features_WASHinSchoolsConstantDrinkingWaterAvailability_11 = format_WASHinSchoolsConstantDrinkingWaterAvailability_11.readFeatures(json_WASHinSchoolsConstantDrinkingWaterAvailability_11, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsConstantDrinkingWaterAvailability_11 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsConstantDrinkingWaterAvailability_11.addFeatures(features_WASHinSchoolsConstantDrinkingWaterAvailability_11);
var lyr_WASHinSchoolsConstantDrinkingWaterAvailability_11 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsConstantDrinkingWaterAvailability_11, 
                style: style_WASHinSchoolsConstantDrinkingWaterAvailability_11,
                popuplayertitle: 'WASH in Schools — Constant Drinking Water Availability',
                interactive: true,
    title: 'WASH in Schools — Constant Drinking Water Availability<br />\
    <img src="styles/legend/WASHinSchoolsConstantDrinkingWaterAvailability_11_0.png" /> No (unavailable less than 30 days total)<br />\
    <img src="styles/legend/WASHinSchoolsConstantDrinkingWaterAvailability_11_1.png" /> Don\'t know, can\'t say<br />\
    <img src="styles/legend/WASHinSchoolsConstantDrinkingWaterAvailability_11_2.png" /> Mostly (unavailable more than 30 days total)<br />\
    <img src="styles/legend/WASHinSchoolsConstantDrinkingWaterAvailability_11_3.png" /> Yes (always available)<br />' });
var format_WASHinSchoolsMainSourceofDrinkingWater_12 = new ol.format.GeoJSON();
var features_WASHinSchoolsMainSourceofDrinkingWater_12 = format_WASHinSchoolsMainSourceofDrinkingWater_12.readFeatures(json_WASHinSchoolsMainSourceofDrinkingWater_12, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsMainSourceofDrinkingWater_12 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsMainSourceofDrinkingWater_12.addFeatures(features_WASHinSchoolsMainSourceofDrinkingWater_12);
var lyr_WASHinSchoolsMainSourceofDrinkingWater_12 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsMainSourceofDrinkingWater_12, 
                style: style_WASHinSchoolsMainSourceofDrinkingWater_12,
                popuplayertitle: 'WASH in Schools — Main Source of Drinking Water',
                interactive: true,
    title: 'WASH in Schools — Main Source of Drinking Water<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_0.png" /> No water source<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_1.png" /> Packaged bottled water<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_2.png" /> Water brought by kids from home<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_3.png" /> Unprotected, uncovered well, spring<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_4.png" /> Surface water (lagoon, river, stream,sea)<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_5.png" /> Rainwater<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_6.png" /> Tanker truck or cart<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_7.png" /> Piped water supply, Tap Stan<br />\
    <img src="styles/legend/WASHinSchoolsMainSourceofDrinkingWater_12_8.png" /> Protected, covered well with pump<br />' });
var format_WASHinSchoolsType_13 = new ol.format.GeoJSON();
var features_WASHinSchoolsType_13 = format_WASHinSchoolsType_13.readFeatures(json_WASHinSchoolsType_13, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsType_13 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsType_13.addFeatures(features_WASHinSchoolsType_13);
var lyr_WASHinSchoolsType_13 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsType_13, 
                style: style_WASHinSchoolsType_13,
                popuplayertitle: 'WASH in Schools — Type',
                interactive: true,
    title: 'WASH in Schools — Type<br />\
    <img src="styles/legend/WASHinSchoolsType_13_0.png" /> Community High School <br />\
    <img src="styles/legend/WASHinSchoolsType_13_1.png" /> Early Childhood Center <br />\
    <img src="styles/legend/WASHinSchoolsType_13_2.png" /> Early Childhood Education Center <br />\
    <img src="styles/legend/WASHinSchoolsType_13_3.png" /> Early Childhood Education Centerl <br />\
    <img src="styles/legend/WASHinSchoolsType_13_4.png" /> Early Childhood Education Centre <br />\
    <img src="styles/legend/WASHinSchoolsType_13_5.png" /> National Secondary School <br />\
    <img src="styles/legend/WASHinSchoolsType_13_6.png" /> Primary School <br />\
    <img src="styles/legend/WASHinSchoolsType_13_7.png" /> Provincial Secondary School <br />\
    <img src="styles/legend/WASHinSchoolsType_13_8.png" /> Rural Training Centre <br />\
    <img src="styles/legend/WASHinSchoolsType_13_9.png" /> Secondary School <br />\
    <img src="styles/legend/WASHinSchoolsType_13_10.png" /> Senior High School <br />' });
var format_WASHinSchoolsNumberofClassrooms_14 = new ol.format.GeoJSON();
var features_WASHinSchoolsNumberofClassrooms_14 = format_WASHinSchoolsNumberofClassrooms_14.readFeatures(json_WASHinSchoolsNumberofClassrooms_14, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsNumberofClassrooms_14 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsNumberofClassrooms_14.addFeatures(features_WASHinSchoolsNumberofClassrooms_14);
var lyr_WASHinSchoolsNumberofClassrooms_14 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsNumberofClassrooms_14, 
                style: style_WASHinSchoolsNumberofClassrooms_14,
                popuplayertitle: 'WASH in Schools — Number of Classrooms',
                interactive: true,
    title: 'WASH in Schools — Number of Classrooms<br />\
    <img src="styles/legend/WASHinSchoolsNumberofClassrooms_14_0.png" /> 0 - 4<br />\
    <img src="styles/legend/WASHinSchoolsNumberofClassrooms_14_1.png" /> 4 - 9<br />\
    <img src="styles/legend/WASHinSchoolsNumberofClassrooms_14_2.png" /> 9 - 16<br />\
    <img src="styles/legend/WASHinSchoolsNumberofClassrooms_14_3.png" /> 16 - 32<br />\
    <img src="styles/legend/WASHinSchoolsNumberofClassrooms_14_4.png" /> 32 - 60<br />' });
var format_WASHinSchoolsSchoolCode_15 = new ol.format.GeoJSON();
var features_WASHinSchoolsSchoolCode_15 = format_WASHinSchoolsSchoolCode_15.readFeatures(json_WASHinSchoolsSchoolCode_15, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsSchoolCode_15 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsSchoolCode_15.addFeatures(features_WASHinSchoolsSchoolCode_15);
var lyr_WASHinSchoolsSchoolCode_15 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsSchoolCode_15, 
                style: style_WASHinSchoolsSchoolCode_15,
                popuplayertitle: 'WASH in Schools — School Code',
                interactive: true,
                title: '<img src="styles/legend/WASHinSchoolsSchoolCode_15.png" /> WASH in Schools — School Code'
            });
var format_WASHinSchoolsName_16 = new ol.format.GeoJSON();
var features_WASHinSchoolsName_16 = format_WASHinSchoolsName_16.readFeatures(json_WASHinSchoolsName_16, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_WASHinSchoolsName_16 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_WASHinSchoolsName_16.addFeatures(features_WASHinSchoolsName_16);
var lyr_WASHinSchoolsName_16 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_WASHinSchoolsName_16, 
                style: style_WASHinSchoolsName_16,
                popuplayertitle: 'WASH in Schools — Name',
                interactive: true,
                title: '<img src="styles/legend/WASHinSchoolsName_16.png" /> WASH in Schools — Name'
            });

lyr_GoogleSatellite_0.setVisible(true);lyr_SolomonIslands_1.setVisible(true);lyr_WASHinSchoolsBinsforMenstrualMaterials_2.setVisible(false);lyr_WASHinSchoolsNumberofHandwashingFacilities_3.setVisible(false);lyr_WASHinSchoolsAccessibleToiletsforPWD_4.setVisible(false);lyr_WASHinSchoolsNumberofBoysToilets_5.setVisible(false);lyr_WASHinSchoolsNumberofGirlsToilets_6.setVisible(false);lyr_WASHinSchoolsGenderSeparatedToilets_7.setVisible(false);lyr_WASHinSchoolsNumberofStudentToilets_8.setVisible(false);lyr_WASHinSchoolsNumberofDrinkingWaterPoints_9.setVisible(false);lyr_WASHinSchoolsDrinkingWaterforPWD_10.setVisible(false);lyr_WASHinSchoolsConstantDrinkingWaterAvailability_11.setVisible(false);lyr_WASHinSchoolsMainSourceofDrinkingWater_12.setVisible(false);lyr_WASHinSchoolsType_13.setVisible(false);lyr_WASHinSchoolsNumberofClassrooms_14.setVisible(false);lyr_WASHinSchoolsSchoolCode_15.setVisible(false);lyr_WASHinSchoolsName_16.setVisible(true);
var layersList = [lyr_GoogleSatellite_0,lyr_SolomonIslands_1,lyr_WASHinSchoolsBinsforMenstrualMaterials_2,lyr_WASHinSchoolsNumberofHandwashingFacilities_3,lyr_WASHinSchoolsAccessibleToiletsforPWD_4,lyr_WASHinSchoolsNumberofBoysToilets_5,lyr_WASHinSchoolsNumberofGirlsToilets_6,lyr_WASHinSchoolsGenderSeparatedToilets_7,lyr_WASHinSchoolsNumberofStudentToilets_8,lyr_WASHinSchoolsNumberofDrinkingWaterPoints_9,lyr_WASHinSchoolsDrinkingWaterforPWD_10,lyr_WASHinSchoolsConstantDrinkingWaterAvailability_11,lyr_WASHinSchoolsMainSourceofDrinkingWater_12,lyr_WASHinSchoolsType_13,lyr_WASHinSchoolsNumberofClassrooms_14,lyr_WASHinSchoolsSchoolCode_15,lyr_WASHinSchoolsName_16];
lyr_SolomonIslands_1.set('fieldAliases', {'OBJECTID': 'OBJECTID', 'ADM3_CODE': 'ADM3_CODE', 'ADM2_CODE': 'ADM2_CODE', 'ADM1_CODE': 'ADM1_CODE', 'ADM0_CODE': 'ADM0_CODE', 'ADM3_NAME': 'ADM3_NAME', 'ADM2_NAME': 'ADM2_NAME', 'ADM1_NAME': 'ADM1_NAME', 'ADM0_NAME': 'ADM0_NAME', 'hz1': 'Tropical Cyclone', 'hz2': 'Heavy Rainfall', 'hz3': 'High Temperature', 'hz4': 'Storm Surge', 'hz5': 'Drought', 'hz6': 'Riverine Flood', 'hz7': 'Landslides', 'hzcom1': 'Climatic', 'hz8': 'Earthquake', 'hz9': 'Tsunami', 'hz10': 'Volcanic Eruption', 'hz11': 'Vector-borne diseases', 'hz12': 'Water-borne diseases', 'hzcom2': 'Non Climatic', 'hzdim': 'EXPOSURE TO SHOCKS AND STRESSES', 'vu1': 'Critical Infrastructure', 'vu2': 'Communication', 'vu3': 'Assets', 'vucom1': 'Lack of Coping Capacity', 'vu4': 'Child Health', 'vu5': 'Child Nutrition', 'vucom2': 'Health', 'vu6': 'Out of School Children', 'vu7': 'Enrollment', 'vu8': 'Gender Parity Index', 'vu9': 'Pupil Teacher to Ratio', 'vu10': 'Education Infrastructure', 'vu11': 'Learning Outcome', 'vucom3': 'Education', 'vu12': 'WASH in School', 'vu13': 'WASH in HCF', 'vu14': 'WASH in Communities', 'vucom4': 'WASH', 'vu15': 'Legal Identity', 'vu16': 'Violence, Abuse & Exploitation', 'vucom5': 'Child Protection', 'vu17': 'Poverty and Dependence', 'vu18': 'Social Protection', 'vu19': 'Food Security', 'vucom6': 'Livelihoods & Social Protection', 'vudim': 'CHILD VULNERABILITY', 'ccri_score': 'Childrens Climate and Disaster Risk Index', 'hzclass': 'EX CLASS', 'vuclass': 'VU CLASS', 'ccri_class': 'CCRI CLASS', 'Shape_Length': 'Shape_Length', 'Shape_Area': 'Shape_Area', });
lyr_WASHinSchoolsBinsforMenstrualMaterials_2.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsNumberofHandwashingFacilities_3.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsAccessibleToiletsforPWD_4.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsNumberofBoysToilets_5.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsNumberofGirlsToilets_6.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsGenderSeparatedToilets_7.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsNumberofStudentToilets_8.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsNumberofDrinkingWaterPoints_9.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsDrinkingWaterforPWD_10.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsConstantDrinkingWaterAvailability_11.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsMainSourceofDrinkingWater_12.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsType_13.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsNumberofClassrooms_14.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsSchoolCode_15.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_WASHinSchoolsName_16.set('fieldAliases', {'fid': 'fid', 'datapoint_name': 'datapoint_name', 'Province': 'Province', 'Type': 'Type', 'Name': 'Name', 'School Code': 'School Code', 'WARD': 'WARD', 'Latitude': 'Latitude', 'Longitude': 'Longitude', 'Number of classrooms': 'Number of classrooms', 'Number of Girls': 'Number of Girls', 'Number of Boys': 'Number of Boys', 'Number of female teachers': 'Number of female teachers', 'Number of Male Teachers': 'Number of Male Teachers', 'Primary / main point of drinking water': 'Primary / main point of drinking water', 'Drinking water availability throughout the school year': 'Drinking water availability throughout the school year', 'Drinking water accessibility for those with limited mobility or vision?': 'Drinking water accessibility for those with limited mobility or vision?', 'Number of drinking water points': 'Number of drinking water points', 'Number of student Toilets': 'Number of student Toilets', 'Separate toilets or latrines for girls and boys': 'Separate toilets or latrines for girls and boys', 'Available toilets for girls': 'Available toilets for girls', 'Available toilets for boys': 'Available toilets for boys', 'Toilet available for those with limited mobility or vision?': 'Toilet available for those with limited mobility or vision?', 'Number of handwashing facilities': 'Number of handwashing facilities', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'Availability of covered bins for disposal of menstrual materials in the toilets', 'Annual government funding': 'Annual government funding', });
lyr_SolomonIslands_1.set('fieldImages', {'OBJECTID': 'TextEdit', 'ADM3_CODE': 'TextEdit', 'ADM2_CODE': 'TextEdit', 'ADM1_CODE': 'TextEdit', 'ADM0_CODE': 'TextEdit', 'ADM3_NAME': 'TextEdit', 'ADM2_NAME': 'TextEdit', 'ADM1_NAME': 'TextEdit', 'ADM0_NAME': 'TextEdit', 'hz1': 'TextEdit', 'hz2': 'TextEdit', 'hz3': 'TextEdit', 'hz4': 'TextEdit', 'hz5': 'TextEdit', 'hz6': 'TextEdit', 'hz7': 'TextEdit', 'hzcom1': 'TextEdit', 'hz8': 'TextEdit', 'hz9': 'TextEdit', 'hz10': 'TextEdit', 'hz11': 'TextEdit', 'hz12': 'TextEdit', 'hzcom2': 'TextEdit', 'hzdim': 'TextEdit', 'vu1': 'TextEdit', 'vu2': 'TextEdit', 'vu3': 'TextEdit', 'vucom1': 'TextEdit', 'vu4': 'TextEdit', 'vu5': 'TextEdit', 'vucom2': 'TextEdit', 'vu6': 'TextEdit', 'vu7': 'TextEdit', 'vu8': 'TextEdit', 'vu9': 'TextEdit', 'vu10': 'TextEdit', 'vu11': 'TextEdit', 'vucom3': 'TextEdit', 'vu12': 'TextEdit', 'vu13': 'TextEdit', 'vu14': 'TextEdit', 'vucom4': 'TextEdit', 'vu15': 'TextEdit', 'vu16': 'TextEdit', 'vucom5': 'TextEdit', 'vu17': 'TextEdit', 'vu18': 'TextEdit', 'vu19': 'TextEdit', 'vucom6': 'TextEdit', 'vudim': 'TextEdit', 'ccri_score': 'TextEdit', 'hzclass': 'TextEdit', 'vuclass': 'TextEdit', 'ccri_class': 'TextEdit', 'Shape_Length': 'TextEdit', 'Shape_Area': 'TextEdit', });
lyr_WASHinSchoolsBinsforMenstrualMaterials_2.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsNumberofHandwashingFacilities_3.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsAccessibleToiletsforPWD_4.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsNumberofBoysToilets_5.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsNumberofGirlsToilets_6.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsGenderSeparatedToilets_7.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsNumberofStudentToilets_8.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsNumberofDrinkingWaterPoints_9.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsDrinkingWaterforPWD_10.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsConstantDrinkingWaterAvailability_11.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsMainSourceofDrinkingWater_12.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsType_13.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsNumberofClassrooms_14.set('fieldImages', {'fid': 'TextEdit', 'datapoint_name': 'TextEdit', 'Province': 'TextEdit', 'Type': 'TextEdit', 'Name': 'TextEdit', 'School Code': 'TextEdit', 'WARD': 'TextEdit', 'Latitude': 'TextEdit', 'Longitude': 'TextEdit', 'Number of classrooms': 'Range', 'Number of Girls': 'Range', 'Number of Boys': 'Range', 'Number of female teachers': 'Range', 'Number of Male Teachers': 'Range', 'Primary / main point of drinking water': 'TextEdit', 'Drinking water availability throughout the school year': 'TextEdit', 'Drinking water accessibility for those with limited mobility or vision?': 'TextEdit', 'Number of drinking water points': 'Range', 'Number of student Toilets': 'Range', 'Separate toilets or latrines for girls and boys': 'TextEdit', 'Available toilets for girls': 'Range', 'Available toilets for boys': 'Range', 'Toilet available for those with limited mobility or vision?': 'CheckBox', 'Number of handwashing facilities': 'Range', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'TextEdit', 'Annual government funding': 'TextEdit', });
lyr_WASHinSchoolsSchoolCode_15.set('fieldImages', {'fid': '', 'datapoint_name': '', 'Province': '', 'Type': '', 'Name': '', 'School Code': '', 'WARD': '', 'Latitude': '', 'Longitude': '', 'Number of classrooms': '', 'Number of Girls': '', 'Number of Boys': '', 'Number of female teachers': '', 'Number of Male Teachers': '', 'Primary / main point of drinking water': '', 'Drinking water availability throughout the school year': '', 'Drinking water accessibility for those with limited mobility or vision?': '', 'Number of drinking water points': '', 'Number of student Toilets': '', 'Separate toilets or latrines for girls and boys': '', 'Available toilets for girls': '', 'Available toilets for boys': '', 'Toilet available for those with limited mobility or vision?': '', 'Number of handwashing facilities': '', 'Availability of covered bins for disposal of menstrual materials in the toilets': '', 'Annual government funding': '', });
lyr_WASHinSchoolsName_16.set('fieldImages', {'fid': '', 'datapoint_name': '', 'Province': '', 'Type': '', 'Name': '', 'School Code': '', 'WARD': '', 'Latitude': '', 'Longitude': '', 'Number of classrooms': '', 'Number of Girls': '', 'Number of Boys': '', 'Number of female teachers': '', 'Number of Male Teachers': '', 'Primary / main point of drinking water': '', 'Drinking water availability throughout the school year': '', 'Drinking water accessibility for those with limited mobility or vision?': '', 'Number of drinking water points': '', 'Number of student Toilets': '', 'Separate toilets or latrines for girls and boys': '', 'Available toilets for girls': '', 'Available toilets for boys': '', 'Toilet available for those with limited mobility or vision?': '', 'Number of handwashing facilities': '', 'Availability of covered bins for disposal of menstrual materials in the toilets': '', 'Annual government funding': '', });
lyr_SolomonIslands_1.set('fieldLabels', {'OBJECTID': 'hidden field', 'ADM3_CODE': 'hidden field', 'ADM2_CODE': 'hidden field', 'ADM1_CODE': 'hidden field', 'ADM0_CODE': 'hidden field', 'ADM3_NAME': 'hidden field', 'ADM2_NAME': 'hidden field', 'ADM1_NAME': 'hidden field', 'ADM0_NAME': 'hidden field', 'hz1': 'hidden field', 'hz2': 'hidden field', 'hz3': 'hidden field', 'hz4': 'hidden field', 'hz5': 'hidden field', 'hz6': 'hidden field', 'hz7': 'hidden field', 'hzcom1': 'hidden field', 'hz8': 'hidden field', 'hz9': 'hidden field', 'hz10': 'hidden field', 'hz11': 'hidden field', 'hz12': 'hidden field', 'hzcom2': 'hidden field', 'hzdim': 'hidden field', 'vu1': 'hidden field', 'vu2': 'hidden field', 'vu3': 'hidden field', 'vucom1': 'hidden field', 'vu4': 'hidden field', 'vu5': 'hidden field', 'vucom2': 'hidden field', 'vu6': 'hidden field', 'vu7': 'hidden field', 'vu8': 'hidden field', 'vu9': 'hidden field', 'vu10': 'hidden field', 'vu11': 'hidden field', 'vucom3': 'hidden field', 'vu12': 'hidden field', 'vu13': 'hidden field', 'vu14': 'hidden field', 'vucom4': 'hidden field', 'vu15': 'hidden field', 'vu16': 'hidden field', 'vucom5': 'hidden field', 'vu17': 'hidden field', 'vu18': 'hidden field', 'vu19': 'hidden field', 'vucom6': 'hidden field', 'vudim': 'hidden field', 'ccri_score': 'hidden field', 'hzclass': 'hidden field', 'vuclass': 'hidden field', 'ccri_class': 'hidden field', 'Shape_Length': 'hidden field', 'Shape_Area': 'hidden field', });
lyr_WASHinSchoolsBinsforMenstrualMaterials_2.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'header label - always visible', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsNumberofHandwashingFacilities_3.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'hidden field', 'School Code': 'hidden field', 'WARD': 'hidden field', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'hidden field', 'Number of Boys': 'hidden field', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsAccessibleToiletsforPWD_4.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'header label - visible with data', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'header label - always visible', 'Separate toilets or latrines for girls and boys': 'header label - always visible', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'header label - always visible', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsNumberofBoysToilets_5.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'header label - always visible', 'Separate toilets or latrines for girls and boys': 'header label - always visible', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'header label - always visible', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsNumberofGirlsToilets_6.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'header label - always visible', 'Separate toilets or latrines for girls and boys': 'header label - always visible', 'Available toilets for girls': 'header label - always visible', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsGenderSeparatedToilets_7.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'header label - always visible', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsNumberofStudentToilets_8.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'hidden field', 'School Code': 'hidden field', 'WARD': 'hidden field', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'hidden field', 'Number of Boys': 'hidden field', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsNumberofDrinkingWaterPoints_9.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'header label - always visible', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'header label - always visible', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsDrinkingWaterforPWD_10.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'header label - always visible', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsConstantDrinkingWaterAvailability_11.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'header label - always visible', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'header label - always visible', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsMainSourceofDrinkingWater_12.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'header label - always visible', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'header label - always visible', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'header label - always visible', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsType_13.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'header label - always visible', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'hidden field', 'Number of Boys': 'hidden field', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsNumberofClassrooms_14.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'hidden field', 'WARD': 'hidden field', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'header label - always visible', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsSchoolCode_15.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'header label - always visible', 'School Code': 'header label - always visible', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'hidden field', 'Number of Boys': 'hidden field', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsName_16.set('fieldLabels', {'fid': 'hidden field', 'datapoint_name': 'hidden field', 'Province': 'hidden field', 'Type': 'hidden field', 'Name': 'hidden field', 'School Code': 'hidden field', 'WARD': 'header label - always visible', 'Latitude': 'hidden field', 'Longitude': 'hidden field', 'Number of classrooms': 'hidden field', 'Number of Girls': 'header label - always visible', 'Number of Boys': 'header label - always visible', 'Number of female teachers': 'hidden field', 'Number of Male Teachers': 'hidden field', 'Primary / main point of drinking water': 'hidden field', 'Drinking water availability throughout the school year': 'hidden field', 'Drinking water accessibility for those with limited mobility or vision?': 'hidden field', 'Number of drinking water points': 'hidden field', 'Number of student Toilets': 'hidden field', 'Separate toilets or latrines for girls and boys': 'hidden field', 'Available toilets for girls': 'hidden field', 'Available toilets for boys': 'hidden field', 'Toilet available for those with limited mobility or vision?': 'hidden field', 'Number of handwashing facilities': 'hidden field', 'Availability of covered bins for disposal of menstrual materials in the toilets': 'hidden field', 'Annual government funding': 'hidden field', });
lyr_WASHinSchoolsName_16.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});